<a href="https://colab.research.google.com/github/sonhj110/SESAC_lecture/blob/master/%EB%94%A5%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88(%EC%A7%80%EB%8F%84%ED%95%99%EC%8A%B5_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1%ED%9A%8C%EA%B7%80).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습1 - 텐서플로우로 선형회귀 모델링

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

x = np.array([2,4,6,8,10])
y = np.array([20,24,37,40,50])

In [ ]:
model = Sequential()  # 모델 선언

model.add(Dense(1, input_dim = 1, activation = 'linear'))
# ‘add’ : 신경망 모델 쌓기
# ‘Dense’ : 각 층의 입력과 출력을 연결
# 인풋 차원 = 1, 활성화 함수 = 선형회귀

model.compile(loss='mse', optimizer = 'sgd', metrics = ['accuracy'])
# ‘Compile’ : 딥러닝 모델 실행
# 손실함수 mean square error, 옵티마이저 sgd

In [ ]:
model.summary()  # 내가 만든 모델 확인할 수 있음

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x, y, epochs = 10)  # epochs 학습 반복 횟수
# ‘fit’ : 딥러닝 모델 학습

Epoch 1/10
1/1 [==============================] - 1s 556ms/step - loss: 660.0298 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 32.0558 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 25.1688 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 24.9451 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 24.7939 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 24.6446 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 24.4963 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 24.3491 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 24.2030 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 24.0578 - 

In [ ]:
model.predict([5])  # 에측하기

1/1 [==============================] - 0s 91ms/step


array([[27.086037]], dtype=float32)

# 실습2 - 텐서플로우로 선형회귀 모델링(2차원)

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

x = np.array([[2,0],[4,5],[6,3],[8,5],[10,7]])  # x값의 차원 y값에 대응되는 x값의 개수
y = np.array([20,24,37,40,50])

In [ ]:
model2 = Sequential()

model2.add(Dense(1, input_dim = 2, activation = 'linear'))

model2.compile(loss = 'mse', optimizer = 'sgd', metrics = ['accuracy'])
model2.fit(x, y, epochs = 10)

Epoch 1/10
1/1 [==============================] - 0s 479ms/step - loss: 1266.9102 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 21ms/step - loss: 153.7502 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 14ms/step - loss: 49.1877 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 14ms/step - loss: 38.5747 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 15ms/step - loss: 36.7453 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 35.7680 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 34.9027 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 34.0789 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 33.2887 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 32.530

In [ ]:
model2.predict([[5,7]])

1/1 [==============================] - 0s 36ms/step


array([[31.289927]], dtype=float32)

# 실습3 - 텐서플로우로 로지스틱 회귀 모델링
로지스틱회귀 : 출력값이 0 아니면 1, 분류모델용

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

x = np.array([2,4,6,8,10])
y = np.array([0,0,0,1,1])

In [ ]:
model3 = Sequential()

model3.add(Dense(1, input_dim = 1, activation = 'sigmoid'))

model3.compile(loss = 'binary_crossentropy', optimizer = 'sgd', metrics = ['accuracy'])
model3.fit(x, y, epochs = 50)

Epoch 1/50
1/1 [==============================] - 1s 512ms/step - loss: 0.7960 - accuracy: 0.6000
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 0.7723 - accuracy: 0.6000
Epoch 3/50
1/1 [==============================] - 0s 17ms/step - loss: 0.7530 - accuracy: 0.6000
Epoch 4/50
1/1 [==============================] - 0s 11ms/step - loss: 0.7375 - accuracy: 0.6000
Epoch 5/50
1/1 [==============================] - 0s 12ms/step - loss: 0.7250 - accuracy: 0.6000
Epoch 6/50
1/1 [==============================] - 0s 11ms/step - loss: 0.7150 - accuracy: 0.6000
Epoch 7/50
1/1 [==============================] - 0s 15ms/step - loss: 0.7070 - accuracy: 0.6000
Epoch 8/50
1/1 [==============================] - 0s 13ms/step - loss: 0.7007 - accuracy: 0.6000
Epoch 9/50
1/1 [==============================] - 0s 16ms/step - loss: 0.6956 - accuracy: 0.6000
Epoch 10/50
1/1 [==============================] - 0s 14ms/step - loss: 0.6915 - accuracy: 0.4000
Epoch 11/50
1/1 [===========

In [ ]:
model3.predict([3])

1/1 [==============================] - 0s 148ms/step


array([[0.5293646]], dtype=float32)